# Generated by Django 4.0.2 on 2022-02-25 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('idCamara', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('usercam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('Horainicio', models.TimeField()),
                ('Horafin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('idTelefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('chatid', models.CharField(blank=True, max_length=20)),
                ('usertel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skedul',
            fields=[
                ('idSkedul', models.AutoField(primary_key=True, serialize=False)),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.horario')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(editable=False, max_length=255)),
                ('etiqueta', models.CharField(blank=True, max_length=2, null=True)),
                ('camname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camara')),
            ],
        ),
        migrations.CreateModel(
            name='Camtel',
            fields=[
                ('idCamtel', models.AutoField(primary_key=True, serialize=False)),
                ('idCamara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camara')),
                ('idSkedul', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vibackend.skedul')),
                ('idTelefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('idCamtel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camtel')),
                ('idFoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibackend.foto')),
            ],
        ),
    ]
