# Generated by Django 4.0.2 on 2022-02-15 13:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
            managers=[
                ('camaras', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('chatid', models.CharField(max_length=20)),
                ('camaras', models.ManyToManyField(to='vibackend.camara')),
            ],
        ),
    ]
