# Generated by Django 4.0.3 on 2022-03-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('idCamara', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('usercam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camtel',
            fields=[
                ('idCamtel', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, default=False)),
                ('idCamara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camara')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('idDia', models.AutoField(primary_key=True, serialize=False)),
                ('Dia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('idTelefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('chatid', models.CharField(blank=True, max_length=20)),
                ('fullDay', models.BooleanField(blank=True, default=False)),
                ('usertel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('Horainicio', models.CharField(default='00:00', max_length=5)),
                ('Horafin', models.CharField(default='23:59', max_length=5)),
                ('diaHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.dia')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('etiqueta', models.BooleanField(blank=True, null=True)),
                ('camname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camara')),
            ],
        ),
        migrations.CreateModel(
            name='Camtelhorario',
            fields=[
                ('idCamtelHorario', models.AutoField(primary_key=True, serialize=False)),
                ('idCamtel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camtel')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.horario')),
            ],
        ),
        migrations.AddField(
            model_name='camtel',
            name='idTelefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.telefono'),
        ),
        migrations.AddField(
            model_name='camtel',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('idCamtelHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camtelhorario')),
                ('idFoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibackend.foto')),
            ],
        ),
    ]
