# Generated by Django 4.0.3 on 2022-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='path',
            field=models.ImageField(blank=True, default='media/2022-03-30,09-13-47.png', max_length=500, null=True, upload_to='media/'),
        ),
    ]
