# Generated by Django 4.0.2 on 2022-03-02 15:09

from django.db import migrations, models
import django.db.models.deletion
import vidgear.gears.camgear


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0002_camara_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('idStream', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=(vidgear.gears.camgear.CamGear, models.Model),
        ),
        migrations.RemoveField(
            model_name='camara',
            name='stream',
        ),
        migrations.AddField(
            model_name='camara',
            name='streCam',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='vibackend.stream'),
            preserve_default=False,
        ),
    ]
