# Generated by Django 4.0.2 on 2022-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0003_stream_remove_camara_stream_camara_strecam'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='source',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
