# Generated by Django 4.0.2 on 2022-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0006_dia_remove_horario_dia_horario_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='Horafin',
            field=models.CharField(default='23:59', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Horainicio',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
