# Generated by Django 4.0.2 on 2022-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0007_alter_horario_horafin_alter_horario_horainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='fullDay',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='camtel',
            name='activo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
