# Generated by Django 4.0.2 on 2022-03-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0008_alerta_fullday_camtel_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camtelhorario',
            fields=[
                ('idCamtelHorario', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='camtel',
            name='idSkedul',
        ),
        migrations.DeleteModel(
            name='Skedul',
        ),
        migrations.AddField(
            model_name='camtelhorario',
            name='idCamtel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.camtel'),
        ),
        migrations.AddField(
            model_name='camtelhorario',
            name='idHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibackend.horario'),
        ),
    ]
