# Generated by Django 4.0.2 on 2022-03-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0010_camtel_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='idCamtel',
        ),
        migrations.AddField(
            model_name='alerta',
            name='idCamtelHorario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vibackend.camtelhorario'),
            preserve_default=False,
        ),
    ]
