# Generated by Django 4.0.2 on 2022-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0011_remove_alerta_idcamtel_alerta_idcamtelhorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='fullDay',
        ),
        migrations.AddField(
            model_name='telefono',
            name='fullDay',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
