# Generated by Django 4.0.2 on 2022-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0012_remove_alerta_fullday_telefono_fullday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
