# Generated by Django 4.0.2 on 2022-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibackend', '0014_alter_foto_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='etiqueta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
